# Generated by Django 4.0.2 on 2023-06-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_auctions_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
